### ISSUE TITLE
[0.5pt] Find external API - group task

### ISSUE THREAD

**Issue by StarSheriff2** [StarSheriff2/Javascript-API-Page#20]
Find an API to base the development of the webapp around it. The API should allow you to
  - Get a list of items with a unique item id (or generate the unique id).
  - For a given item, get detailed information about it.
choose an APIs that doesn't need authentication. if you select an API that requires authentication, you should implement it on your own. Also, if you select an API that provides image resources your webapp will be more visual.

**Comment by vichuge** [comment]
# Project invalidated 🚫 

Hi there, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![cat_massage](https://user-images.githubusercontent.com/20563252/121368971-16d2dc00-c901-11eb-9123-7f578bf64118.gif)

## Why does this happen ❓ ❓ ❓ 

You have submitted a project, that has sent an empty repository, please, send a link to an issue.
`Students should have sent you a link to the GitHub issue that has a link to the GitHub project.`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
