### ISSUE TITLE
JS-Capstone-Project

### ISSUE THREAD

**Issue by StarSheriff2** [StarSheriff2/Javascript-API-Page#21]
Hi Code Reviewer,

This is the link to the repo: https://github.com/StarSheriff2/Javascript-API-Page/projects/1

We are 2 students in total in this project:

- Student A: https://github.com/StarSheriff2
- Student B: https://github.com/jchernandez87

**Comment by Dipeshtwis** [comment]
Hi @StarSheriff2 and @jchernandez87, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [x] You have done a great job, but the link you have provided in the issue description is not the one supposed to be, it should be a link to your Projects :point_right: [look at this, please](https://github.com/StarSheriff2/Javascript-API-Page/projects/1).

- [x] The issue should use a circle with the user's avatar on each card. See the example below:

<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/22434660/127869037-f6a6909b-7c2e-4da8-a6cb-f2e1ff326702.png">

### Your's issue card look like:

![Screenshot from 2021-08-03 02-42-51](https://user-images.githubusercontent.com/22434660/127924681-cad04c3b-2905-43df-9490-3d8ea7af8fa1.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- It's better if you mention the two names and also link who is person A and person B in [this issue](https://github.com/Ghiftee/Microverse-Js-capstone/issues/18#issue-958102835) description.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by henatan99** [comment]
Hi team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [x] The first thing you need to change is the link you should provide in the issue comment box. You should give the [project link](https://github.com/StarSheriff2/Javascript-API-Page/projects/1).
- [x] You should assign tasks in a fairway. That means if one of you starts as Student-A, then he/she should be assigned to tasks of all student A. I saw you mix it up. 
- [x] Kindly make the requested changes and submit for another review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by StarSheriff2** [comment]
Hi Henok,

Thanks for the review. In your second point, you mention that we mixed up the tasks; however, we assigned tasks for Student A, to the project member who is Student A, and all Student B tasks to the person assigned as Student B.

**Comment by vichuge** [comment]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
